//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xprema.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Transactions = new List<Transaction>();
            this.ProjectActivities = new List<ProjectActivity>();
            this.ProjectExpenses = new List<ProjectExpens>();
            this.ProjectProfiles = new List<ProjectProfile>();
            this.ProjectSubActivities = new List<ProjectSubActivity>();
            this.Thefinanciers = new List<Thefinancier>();
        }
    
        public int ID { get; set; }
        public string AccountName { get; set; }
        public string AccountDescription { get; set; }
        public string Coin { get; set; }
        public string AccountNatural { get; set; }

        public virtual List<Transaction> Transactions { get; set; }
        public virtual List<ProjectActivity> ProjectActivities { get; set; }
        public virtual List<ProjectExpens> ProjectExpenses { get; set; }
        public virtual List<ProjectProfile> ProjectProfiles { get; set; }
        public virtual List<ProjectSubActivity> ProjectSubActivities { get; set; }
        public virtual List<Thefinancier> Thefinanciers { get; set; }
    }
}
