//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xprema.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();
            this.ProjectActivities = new HashSet<ProjectActivity>();
            this.ProjectExpenses = new HashSet<ProjectExpens>();
            this.ProjectProfiles = new HashSet<ProjectProfile>();
            this.ProjectSubActivities = new HashSet<ProjectSubActivity>();
            this.Thefinanciers = new HashSet<Thefinancier>();
        }
    
        public int ID { get; set; }
        public string AccountName { get; set; }
        public string AccountDescription { get; set; }
        public string Coin { get; set; }
        public string AccountNatural { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<ProjectActivity> ProjectActivities { get; set; }
        public virtual ICollection<ProjectExpens> ProjectExpenses { get; set; }
        public virtual ICollection<ProjectProfile> ProjectProfiles { get; set; }
        public virtual ICollection<ProjectSubActivity> ProjectSubActivities { get; set; }
        public virtual ICollection<Thefinancier> Thefinanciers { get; set; }
    }
}
