//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xprema.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int ID { get; set; }
        public string AttachmentName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte[] fileContent { get; set; }
        public Nullable<int> ProjectProfile_ID { get; set; }
        public Nullable<int> ProjectOrder_ID { get; set; }
    
        public virtual ProjectOrder ProjectOrder { get; set; }
        public virtual ProjectProfile ProjectProfile { get; set; }
    }
}
