//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xprema.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Xprema_PrjectEntities : DbContext
    {
        public Xprema_PrjectEntities()
            : base("name=Xprema_PrjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<DailyMovemnt> DailyMovemnts { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<GroupPermession> GroupPermessions { get; set; }
        public virtual DbSet<ProjectActivity> ProjectActivities { get; set; }
        public virtual DbSet<ProjectExpens> ProjectExpenses { get; set; }
        public virtual DbSet<ProjectOrder> ProjectOrders { get; set; }
        public virtual DbSet<ProjectProfile> ProjectProfiles { get; set; }
        public virtual DbSet<ProjectSubActivity> ProjectSubActivities { get; set; }
        public virtual DbSet<SubTheFinancerAndProject> SubTheFinancerAndProjects { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<SystemPermession> SystemPermessions { get; set; }
        public virtual DbSet<Thefinancier> Thefinanciers { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserSystem> UserSystems { get; set; }
        public virtual DbSet<View_Account_ByBalance> View_Account_ByBalance { get; set; }
        public virtual DbSet<View_AccountDetails> View_AccountDetails { get; set; }
    }
}
