//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xprema.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectProfile
    {
        public ProjectProfile()
        {
            this.Attachments = new HashSet<Attachment>();
            this.Contracts = new HashSet<Contract>();
            this.ProjectActivities = new HashSet<ProjectActivity>();
            this.ProjectOrders = new HashSet<ProjectOrder>();
            this.SubTheFinancerAndProjects = new HashSet<SubTheFinancerAndProject>();
        }
    
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Status { get; set; }
        public int progress { get; set; }
        public double TotalCost { get; set; }
        public Nullable<int> AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<ProjectActivity> ProjectActivities { get; set; }
        public virtual ICollection<ProjectOrder> ProjectOrders { get; set; }
        public virtual ICollection<SubTheFinancerAndProject> SubTheFinancerAndProjects { get; set; }
    }
}
