//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xprema.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemPermession
    {
        public SystemPermession()
        {
            this.GroupPermessions = new List<GroupPermession>();
        }
    
        public int Id { get; set; }
        public string PermessionName { get; set; }
        public string PropertyName { get; set; }

        public virtual List<GroupPermession> GroupPermessions { get; set; }
    }
}
