//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xprema.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public UserGroup()
        {
            this.GroupPermessions = new List<GroupPermession>();
            this.UserSystems = new List<UserSystem>();
        }
    
        public int Id { get; set; }
        public string GroupName { get; set; }
        public string GroupDescription { get; set; }

        public virtual List<GroupPermession> GroupPermessions { get; set; }
        public virtual List<UserSystem> UserSystems { get; set; }
    }
}
